# Stage 1
FROM node:18.17.0 as node

ENV NODE_OPTIONS=--max_old-space-size=8192

WORKDIR /app
COPY . .
RUN npm install -g npm@10.2.1
RUN npm cache clean --force
RUN npm install --force
RUN npm run build
# Stage 2
FROM nginx:alpine
# Copy the SSL certificates to the container
#COPY cert.crt /etc/ssl/certs/cert.crt
#COPY cert.key /etc/ssl/private/cert.key

# COPY fullchain.pem /etc/ssl/certs/cert.crt
# COPY privkey.pem /etc/ssl/private/cert.key

COPY baycounter.crt /etc/ssl/certs/cert.crt
COPY baycounter.key /etc/ssl/private/cert.key

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d

COPY --from=node /app/dist/angular-parthub /usr/share/nginx/html

# Expose port 443 for HTTPS
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]