# Stage 1
FROM node:18.17.0 as node
WORKDIR /app
COPY . .
RUN npm install -g npm@10.2.1
RUN npm cache clean --force
RUN npm install --force
RUN npm run build
# Stage 2
FROM nginx:alpine
COPY --from=node /app/dist/angular-parthub /usr/share/nginx/html