ALTER TABLE `claims`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `counterinvoices`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `jobs`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `payments`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `purchaseorders`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `purchaseordervehicles`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `receipts`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;

ALTER TABLE `suppllements`
	ADD COLUMN `token` VARCHAR(36) NULL DEFAULT NULL AFTER `id`;